import Arrow from "../../src/assets/image/scroll@3x.png";
import Group from "../../src/assets/image/Group 9.png";
const Section1 =() => {
    return (
        <>
        <div className="sec1_container">
            <img src={Arrow} alt=""/>
         </div>

            <div className="sec1_main">
                <div className="left_sec1">
                    <h2>How to interpret this report?</h2>
                    <img src={Group} alt=""/>
                </div>
                <div className="right_sec1">
                    <p>During the session, you have read a list of 32 words and we have recorded your readings. 16 words are real English words and 16 are nonsense words, generated by Artificial Intelligence techniques. The complete list of words has been generated in accordance with your age. Your audio recordings have been securely sent to and processed on our server. Our systems has analysed the records and estimated the likelihood of dyslexia. We have also computed 6 metrics which are important for the likelihood estimate:</p>
                    <ul>
                        <li>3 metrics are related to what is known as <span>Reading Reaction Time(RRT).</span> For a given word, the reading reaction time is interval between the initial display of the word and the start of your reading. You get an average RRT on all words, on real words and on nonsense words.</li>
                        <li>3 other metrics are related to <span>Reading Time (RT)</span> which is an indication of the time it takes for you to read a word. You get an average RT on all words, on real words and on nonsense words.</li>
                    </ul>
                    <span><p>The unit of time we use in this report is second (s) within 2 decimal points.</p></span>
                </div>
            </div>
        
        </>
    );
};
export default Section1;